README.md
For easy Access to all adding @bprestoncf comments on Meetup reimbursement.
=> Update README.md with @bprestoncf comments on Meetup reimbursement.

README.md
This is just a quick formatted lines with space/tab for better readability. No content change other than the first line removed which was redundant. Please accept as merge & squash to take care the 5 commits as one commit. Thanks.
=> Updated README.md with correct format/space.

meetups/Meetup_Best_Practices.md
- Updated some grammar and reworded sentences for readability
- Removed HTML (all Markdown now)
- Added subsection headers
=> Some rewording and Markdown cleanup.

README.md
Fixes https://github.com/cncf/ambassadors/issues/18
PTAL @caniszczyk
=> Code of Conduct added

meetups/Meetup Reimbursement Policy.md
based on info from @idvoretskyi
=> updated point-of-contact for questions

README.md
As discussed with @caniszczyk.
cc @taylorwaggoner
=> Expenses reimbursement policy updated

README.md
@caniszczyk - let me know if this language sounds good to you 
cc // @idvoretskyi
=> Update Ambassador FAQ

KubeWeekly/kubeweekly-153.md
Tool:
* [Krew](https://github.com/googleContainerTools/krew) 
Editorials:
* [Customizing Kubernetes Logging (Part 1)](https://medium.com/google-cloud/customizing-kubernetes-logging-part-1-a1e5791dcda8)
=> Add content ideas for KW153

BOOKS.md
This PR adds Japanese books into a list of cloud native books.
I'm going to maintain a list of Japanese books.
/cc @idvoretskyi
=> Add Japanese books

BOOKS.md
Hi, @idvoretskyi I'd like to add the books on Cloud Native in Chinese which including the translation, original works, and open source e-books.
=> Add books in Chinese on Cloud Native

BOOKS.md
This PR adds new Japanese books.
=> Add two Japanese books

README.md
Closes https://github.com/cncf/ambassadors/issues/12.
=> Ambassadors map added

EMERITUS.md
Signed-off-by: Jorge O. Castro <jorgec@vmware.com>
=> Move myself to emeritus status

BOOKS.md
Add Kubernetes Best Practices to book list.
Signed-off-by: Lachlan Evenson <lachlan.evenson@gmail.com>
=> (docs/books): Add Kubernetes Best Practices

EMERITUS.md
=> Added __self__ to emeritus ambassadors

meetups/Meetup_Reimbursement_Policy.md
cc @caniszczyk @amye 
Signed-off-by: Ihor Dvoretskyi ihor@linux.com
=> Requests should go to the ServiceDesk first

EMERITUS.md
I never managed to actually engage with the Ambassador-ship position fully (enough to do in Prometheus-land and other places), so I think it'd be best to move myself to an emeritus.
=> Add myself to EMERITUS.md

README.md
Hope other folks won't repeat my mistake and will use existing resources.
=> added a graphic design benefit

EMERITUS.md
I've chatted with Amye S.P. about this change. Please update things, and add me as an emeritus <3
=> Add myself (Paul B) to Emeritus

EMERITUS.md
Hello!
I don't want to hold a such crucial spot! The ambassador program is limited in size, and it is important for all the members to be motivated. I am sure I will find other ways to serve the CNCF community moving forward!
it was a pleasure to be an ambassador!
=> Add myself as Emeritus

Hosting-Cloud-Native-Live.md
* Add Annie and Taylor as current Cloud Native Live hosts
* Add Itay and Mario as emeritus hosts
=> Update Cloud Native Live hosts and emeritus hosts

EMERITUS.md
Shouldn't be an Ambassador and a CNCF employee at the same time. :)
=> emeritus myself :)

EMERITUS.md
Hi,
I need to step down as active Ambassador due to other commitments.
Thank you, it has been pleasure to be an ambassador!
=> Adding myself to EMERITUS.md

1.0/EMERITUS.md
It's been real! Real good. Excited to see where the new CNCF Ambassador class takes the community.
Signed-off-by: Ross Kukulinski <ross@kukulinski.com>
=> Ross stepping down

README.md
=> Update README with new CNCF Ambassador artwork

2.0/Profile.md, 2.0/ReadMe.md, 2.0/monthly-check-in.md
Hi 👋  noticed these typos while reading these docs, HTH
=> docs: typo fixes
